//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        public int ID_Check { get; set; }
        public int Purchases_ID { get; set; }
        public int Flower_ID { get; set; }
        public int Users_ID { get; set; }
    
        public virtual Flower Flower { get; set; }
        public virtual Purchases Purchases { get; set; }
        public virtual Users Users { get; set; }
    }
}
