//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5lab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Flower_shopEntities : DbContext
    {
        public Flower_shopEntities()
            : base("name=Flower_shopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calculation> Calculation { get; set; }
        public virtual DbSet<Checks> Checks { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Flower> Flower { get; set; }
        public virtual DbSet<Flower_type> Flower_type { get; set; }
        public virtual DbSet<Job_title> Job_title { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<Type_of_purchase> Type_of_purchase { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
