//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchases()
        {
            this.Checks = new HashSet<Checks>();
        }
    
        public int ID_Purchases { get; set; }
        public int Calculation_ID { get; set; }
        public int Store_ID { get; set; }
        public string Time_of_buy { get; set; }
        public int Type_of_purchase_ID { get; set; }
    
        public virtual Calculation Calculation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual Store Store { get; set; }
        public virtual Type_of_purchase Type_of_purchase { get; set; }
    }
}
